import test from 'node:test';
import assert from 'node:assert/strict';
import { analyzeCode } from '../src/heuristic.js';

test('returns a reviewable score, rules, and line indexes', () => {
  const report = analyzeCode('// Generated by an AI assistant\nconst customerRecordIdentifier = input;');
  assert.equal(report.score, 41);
  assert.equal(report.matches.length, 2);
  assert.deepEqual([...report.flaggedLines], [0, 1]);
});

test('returns zero when no configured rules match', () => {
  const report = analyzeCode('const x = 1;');
  assert.equal(report.score, 0);
  assert.equal(report.matches.length, 0);
});
