export const defaultRules = [
  {
    name: 'Explicit AI-tool attribution in a comment',
    weight: 34,
    matches: (line) => /\b(chatgpt|copilot|claude|gemini|generated by ai|generated with ai|ai assistant)\b/i.test(line),
  },
  {
    name: 'Boilerplate explanatory comment phrasing',
    weight: 13,
    matches: (line) => /^\s*(\/\/|#|\/\*|\*)\s*(note:|here is|this function|this method|this code|first,|next,|finally,|return a clear|initialize the)/i.test(line),
  },
  {
    name: 'Long documentation-style comment',
    weight: 8,
    matches: (line) => /^\s*(\/\/|#|\/\*|\*|""").{72,}/.test(line),
  },
  {
    name: 'Highly descriptive multi-word identifier',
    weight: 7,
    matches: (line) => /\b(?:function|def|class|public|private|const|let|var)\s+[a-z]+(?:[A-Z][a-z]+){2,}\b/.test(line),
  },
  {
    name: 'Repeated adjacent comments',
    weight: 8,
    matches: (line, index, lines) => index > 0 && /^\s*(\/\/|#|\/\*|\*)/.test(line) && /^\s*(\/\/|#|\/\*|\*)/.test(lines[index - 1]),
  },
  {
    name: 'Template-style defensive error text',
    weight: 6,
    matches: (line) => /throw new (Error|Exception)|raise (ValueError|Exception)/.test(line) && /required|must|cannot|invalid/i.test(line),
  },
];

export function analyzeCode(source, rules = defaultRules) {
  if (typeof source !== 'string') throw new TypeError('source must be a string');
  const lines = source.split(/\r?\n/);
  const flaggedLines = new Set();
  const matches = [];

  for (const rule of rules) {
    const indexes = lines.flatMap((line, index) => rule.matches(line, index, lines) ? [index] : []);
    if (indexes.length) {
      indexes.forEach((index) => flaggedLines.add(index));
      matches.push({ name: rule.name, weight: rule.weight, indexes });
    }
  }

  return {
    lines,
    matches,
    flaggedLines,
    score: Math.min(100, matches.reduce((total, match) => total + match.weight, 0)),
  };
}
